-- Create businesses table
CREATE TABLE public.businesses (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  business_name text NOT NULL,
  ceo_unique_id integer,
  industry text,
  size text,
  website text,
  primary_email text,
  primary_phone text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  zip_code text,
  country text DEFAULT 'US'::text,
  metadata jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT businesses_pkey PRIMARY KEY (id)
);

-- Create user_profiles table (if not exists, or alter it)
-- Note: Assuming user_profiles might already exist or needs to be created fully. 
-- Based on user request, I will create it fully but handle if it exists.
-- Actually, I'll just create it as per the user's SQL. If it conflicts, I'll need to adjust.
-- Given the user provided a full CREATE TABLE, I will assume it's new or replacing.
-- However, to be safe, I'll use CREATE TABLE IF NOT EXISTS and then ALTER.

CREATE TYPE subscription_type AS ENUM ('incomplete', 'active', 'canceled', 'past_due'); 
-- Note: subscription_type might already exist in types_db.ts it was not there, but in schema.sql there was pricing_type. 
-- The user's SQL uses 'incomplete'::subscription_type. I'll define it.

CREATE TABLE IF NOT EXISTS public.user_profiles (
  unique_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  first_name text,
  middle_name text,
  last_name text,
  full_name text,
  subscription_type subscription_type NOT NULL DEFAULT 'incomplete'::subscription_type,
  business_position text, -- Changed from USER-DEFINED to text for flexibility or I can create the enum
  is_business_account boolean DEFAULT false,
  business_name text,
  business_id integer,
  reports_to_unique_id integer,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  phone text,
  avatar_url text,
  timezone text,
  locale text DEFAULT 'en'::text,
  preferences jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_login_at timestamp with time zone,
  email_verified_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (unique_id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_profiles_reports_to_unique_id_fkey FOREIGN KEY (reports_to_unique_id) REFERENCES public.user_profiles(unique_id),
  CONSTRAINT fk_business_id FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);

-- Add FK to businesses for ceo_unique_id (circular dependency handled by adding constraint after)
ALTER TABLE public.businesses 
ADD CONSTRAINT businesses_ceo_unique_id_fkey 
FOREIGN KEY (ceo_unique_id) REFERENCES public.user_profiles(unique_id);

-- Create business_roles table for Custom Roles
CREATE TABLE public.business_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id integer NOT NULL,
  name text NOT NULL,
  permission_level text NOT NULL CHECK (permission_level IN ('manager', 'employee')),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT business_roles_pkey PRIMARY KEY (id),
  CONSTRAINT business_roles_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);

-- Create business_hierarchy table
CREATE TABLE public.business_hierarchy (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  business_id integer NOT NULL,
  employee_unique_id integer NOT NULL,
  manager_unique_id integer,
  role_id uuid, -- Link to custom role
  position_type text NOT NULL CHECK (position_type IN ('manager', 'employee')), -- Permission level
  department text,
  title text,
  hierarchy_level integer NOT NULL DEFAULT 1,
  metadata jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT business_hierarchy_pkey PRIMARY KEY (id),
  CONSTRAINT business_hierarchy_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT business_hierarchy_employee_unique_id_fkey FOREIGN KEY (employee_unique_id) REFERENCES public.user_profiles(unique_id),
  CONSTRAINT business_hierarchy_manager_unique_id_fkey FOREIGN KEY (manager_unique_id) REFERENCES public.user_profiles(unique_id),
  CONSTRAINT business_hierarchy_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.business_roles(id)
);

-- Enable RLS
ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_hierarchy ENABLE ROW LEVEL SECURITY;

-- Policies (Basic draft, can be refined)
-- Users can view their own profile
CREATE POLICY "Users can view own profile" ON public.user_profiles
  FOR SELECT USING (auth.uid() = user_id);

-- Users can view their business
CREATE POLICY "Users can view their business" ON public.businesses
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles
      WHERE user_profiles.user_id = auth.uid()
      AND user_profiles.business_id = businesses.id
    )
  );

-- Users can view roles in their business
CREATE POLICY "Users can view business roles" ON public.business_roles
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles
      WHERE user_profiles.user_id = auth.uid()
      AND user_profiles.business_id = business_roles.business_id
    )
  );

-- Managers can manage roles
CREATE POLICY "Managers can manage roles" ON public.business_roles
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.business_hierarchy bh
      JOIN public.user_profiles up ON up.unique_id = bh.employee_unique_id
      WHERE up.user_id = auth.uid()
      AND bh.position_type = 'manager'
      AND bh.business_id = business_roles.business_id
    )
  );
