/**
 * ASTROLOGY READINGS
 * Stores saved astrology charts for users.
 */
create table astrology_readings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  profile_id bigint, -- Optional reference to user_profiles.unique_id, for consistency with numerology
  
  -- Critical Birth Data
  date_of_birth date not null,
  time_of_birth time not null,
  birth_city text not null,
  birth_country text not null,
  latitude float,  -- Storing coords avoids re-geocoding
  longitude float, 
  
  -- Chart Configuration
  system text not null default 'western', -- 'western' or 'vedic'
  house_system text, -- e.g. 'placidus', 'whole_sign'
  
  -- The full calculated JSON
  chart_data jsonb not null,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table astrology_readings enable row level security;

create policy "Users can view own astrology readings"
  on astrology_readings for select
  using (auth.uid() = user_id);

create policy "Users can insert own astrology readings"
  on astrology_readings for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own astrology readings"
  on astrology_readings for delete
  using (auth.uid() = user_id);
